# Generated by Django 6.0 on 2026-02-24 08:33

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ItineraryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='The exact query string used')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072, help_text='Llama3.2 embedding vector')),
                ('itinerary_json', models.JSONField(help_text='The generated itinerary response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
