# Generated by Django 6.0 on 2026-02-24 09:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0002_savedtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarycache',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, help_text='Nomic embed-text embedding vector'),
        ),
    ]
