# Generated by Django 6.0 on 2026-04-23 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_api', '0003_alter_itinerarycache_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionAspectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=255, unique=True)),
                ('location_type', models.CharField(blank=True, max_length=100)),
                ('located_city', models.CharField(blank=True, max_length=255)),
                ('scenery', models.FloatField(default=0.5)),
                ('cleanliness', models.FloatField(default=0.5)),
                ('crowd_level', models.FloatField(default=0.5)),
                ('value_for_money', models.FloatField(default=0.5)),
                ('accessibility', models.FloatField(default=0.5)),
                ('safety', models.FloatField(default=0.5)),
                ('food_quality', models.FloatField(default=0.5)),
                ('cultural_significance', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['attraction_name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
